---
- name: "vpc"
  hosts: "localhost"
  connection: "local"
  gather_facts: true

  tasks:
     - name: Build VPC
       cloudformation:
          stack_name: "{{stack_name}}"
          region: "{{region}}"
          state: "present"
          template: "templates/vpc_template.yml"
          template_parameters:
            KeyName: "{{key_name}}"
            InstanceType: "{{instance_type}}"
       register: vpc

     - ec2_remote_facts:
         region: "{{region}}"
         filters:
           instance-state-name: running
       register: ec2_info

     - debug: var=ec2_info

     - name: Add EC2 Instances to Hosts
       add_host: 
         hostname: "{{ item.public_ip_address }}"
         groupname: ec2-instances
       with_items: "{{ ec2_info.instances }}"

     - name: Wait For EC2 Port 22 Access
       wait_for:
         state: started
         host: "{{ item.public_dns_name }}"
         port: 22
         delay: 60
         timeout: 320
       with_items: "{{ ec2_info.instances }}"

- hosts: ec2-instances
  gather_facts: true
  become: yes
  connection: ssh
  remote_user: ec2-user

  roles:
    - nodejs
    - loadtest
