service: nodejsBackup

custom:
  bucket: nodejs-backup

provider:
  name: aws
  runtime: nodejs6.10

  region: us-east-1

functions:
  postbackupcopy:
    handler: handler.postbackupcopy
    events:
      - s3: 
           bucket: ${self:custom.bucket}
           event: s3:ObjectCreated:*
