---
    - name: Update Packages
      yum: 
        name: '*'
        state: latest

    - name: Download Nodejs
      get_url:
        url: https://rpm.nodesource.com/setup_6.x
        dest: /tmp/nodejs.sh

    - name: Change Permission to Nodejs Script
      file:
        path: /tmp/nodejs.sh
        mode: 755

    - name: Execute Nodejs Script
      shell: /tmp/nodejs.sh

    - name: Remove Node.js Script
      file:
        path: /tmp/nodejs.sh
        state: absent

    - name: Install Nodejs
      yum: pkg={{item}} state=installed
      with_items:
        - nodejs
        - gcc-c++
        - make

    - name: Copy Nodejs Config Files
      copy:
        src: ../files/app
        dest: /home/ec2-user/
        owner: ec2-user
        group: ec2-user
        mode: 775
    
    - name: Execute Nodejs Script
      command: '/usr/bin/npm install --prefix /home/ec2-user/app'
    
    - name: Set ENV Vars
      template:
        src: aws_creds.j2
        dest: /home/ec2-user/.bashrc
        owner: ec2-user
        group: ec2-user
        mode: 0755

    - name: Install Pm2
      npm:
        name: pm2
        state: present
        global: yes
    
    - name: Start Express Web Server
      command: 'pm2 start /home/ec2-user/app/index.js'
      ignore_errors: true

    - name: Schedule S3 Backup
      cron:
        minute: '10'
        job: aws s3 cp /home/ec2-user/app/access.log s3://nodejs-backup/$(hostname)-$(date +"%Y%m%d%H%M")-access.log
        user: ec2-user
